services:
  db:
    image: mysql:8.0
    container_name: group-queue-mysql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=group_queue
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "${DATABASE_HOST_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-net

  app:
    build: .
    image: group-queue-app
    container_name: group-queue-app-container
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${DATABASE_HOST_NAME}:${DATABASE_PORT}/${DATABASE_NAME}?useSSL=false&allowPublicKeyRetrieval=true
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-net

networks:
  app-net: